[package]
name = "smis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.3.19", features = ["derive"] }
quote = "1.0.32"
thiserror = "1.0.37"
